import { Container } from "react-bootstrap";
import { NavLink } from "react-router-dom";

const ContentTest = () => {
    return ( 
        <Container fluid className="content-test">

            <NavLink to="projects">PROJECTS</NavLink>
            <h1>CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            CONTENT TEST CONTENT TEST CONTENT TEST CONTENT TEST
            </h1>
        </Container>
    );
}
 
export default ContentTest;